In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df_enc = pd.get_dummies(df, drop_first= True)

In [ ]:
df_enc.head()

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,...,who_woman,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,embark_town_Queenstown,embark_town_Southampton,alive_yes
0,0,3,22.0,1,0,7.2500,True,False,True,False,...,False,False,False,False,False,False,False,False,True,False
1,1,1,38.0,1,0,71.2833,False,False,False,False,...,True,False,True,False,False,False,False,False,False,True
2,1,3,26.0,0,0,7.9250,False,True,False,False,...,True,False,False,False,False,False,False,False,True,True
3,1,1,35.0,1,0,53.1000,False,False,False,False,...,True,False,True,False,False,False,False,False,True,True
4,0,3,35.0,0,0,8.0500,True,True,True,False,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
df_enc.isnull().sum()

survived                     0
pclass                       0
age                        177
sibsp                        0
parch                        0
fare                         0
adult_male                   0
alone                        0
sex_male                     0
embarked_Q                   0
embarked_S                   0
class_Second                 0
class_Third                  0
who_man                      0
who_woman                    0
deck_B                       0
deck_C                       0
deck_D                       0
deck_E                       0
deck_F                       0
deck_G                       0
embark_town_Queenstown       0
embark_town_Southampton      0
alive_yes                    0
dtype: int64

In [ ]:
df_enc.isna().sum()

survived                     0
pclass                       0
age                        177
sibsp                        0
parch                        0
fare                         0
adult_male                   0
alone                        0
sex_male                     0
embarked_Q                   0
embarked_S                   0
class_Second                 0
class_Third                  0
who_man                      0
who_woman                    0
deck_B                       0
deck_C                       0
deck_D                       0
deck_E                       0
deck_F                       0
deck_G                       0
embark_town_Queenstown       0
embark_town_Southampton      0
alive_yes                    0
dtype: int64

In [ ]:
df_enc['age'] = df['age'].fillna(df['age'].mean())

In [ ]:
df_enc['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [ ]:
df_enc.isnull().sum()

survived                   0
pclass                     0
age                        0
sibsp                      0
parch                      0
fare                       0
adult_male                 0
alone                      0
sex_male                   0
embarked_Q                 0
embarked_S                 0
class_Second               0
class_Third                0
who_man                    0
who_woman                  0
deck_B                     0
deck_C                     0
deck_D                     0
deck_E                     0
deck_F                     0
deck_G                     0
embark_town_Queenstown     0
embark_town_Southampton    0
alive_yes                  0
dtype: int64

In [ ]:
df_enc.astype(int)

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,...,who_woman,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,embark_town_Queenstown,embark_town_Southampton,alive_yes
0,0,3,22,1,0,7,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1,1,1,38,1,0,71,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
2,1,3,26,0,0,7,0,1,0,0,...,1,0,0,0,0,0,0,0,1,1
3,1,1,35,1,0,53,0,0,0,0,...,1,0,1,0,0,0,0,0,1,1
4,0,3,35,0,0,8,1,1,1,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27,0,0,13,1,1,1,0,...,0,0,0,0,0,0,0,0,1,0
887,1,1,19,0,0,30,0,1,0,0,...,1,1,0,0,0,0,0,0,1,1
888,0,3,29,1,2,23,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
889,1,1,26,0,0,30,1,1,1,0,...,0,0,1,0,0,0,0,0,0,1
890,0,3,32,0,0,7,1,1,1,1,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
from sklearn.model_selection import train_test_split

X = df_enc.drop('survived', axis=1)
y = df_enc['survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [ ]:
print("Train:", X_train.shape)
print("Test:", X_test.shape)

Train: (712, 23)
Test: (179, 23)

In [ ]:
print(y_pred)

[1 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 0 1
 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 0 0 1 0 1 1 1
 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 1 1
 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 0 1 0 0 1 1 1 0 0 0 1 1 1]

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

In [ ]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00        74

    accuracy                           1.00       179
   macro avg       1.00      1.00      1.00       179
weighted avg       1.00      1.00      1.00       179

In [ ]:
confusion_matrix(y_test,y_pred)

array([[105,   0],
       [  0,  74]])

In [ ]:
df_enc

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,...,who_woman,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,embark_town_Queenstown,embark_town_Southampton,alive_yes
0,0,3,22.000000,1,0,7.2500,True,False,True,False,...,False,False,False,False,False,False,False,False,True,False
1,1,1,38.000000,1,0,71.2833,False,False,False,False,...,True,False,True,False,False,False,False,False,False,True
2,1,3,26.000000,0,0,7.9250,False,True,False,False,...,True,False,False,False,False,False,False,False,True,True
3,1,1,35.000000,1,0,53.1000,False,False,False,False,...,True,False,True,False,False,False,False,False,True,True
4,0,3,35.000000,0,0,8.0500,True,True,True,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,True,True,True,False,...,False,False,False,False,False,False,False,False,True,False
887,1,1,19.000000,0,0,30.0000,False,True,False,False,...,True,True,False,False,False,False,False,False,True,True
888,0,3,29.699118,1,2,23.4500,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
889,1,1,26.000000,0,0,30.0000,True,True,True,False,...,False,False,True,False,False,False,False,False,False,True
890,0,3,32.000000,0,0,7.7500,True,True,True,True,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
df_enc.astype(int)

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,...,who_woman,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,embark_town_Queenstown,embark_town_Southampton,alive_yes
0,0,3,22,1,0,7,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1,1,1,38,1,0,71,0,0,0,0,...,1,0,1,0,0,0,0,0,0,1
2,1,3,26,0,0,7,0,1,0,0,...,1,0,0,0,0,0,0,0,1,1
3,1,1,35,1,0,53,0,0,0,0,...,1,0,1,0,0,0,0,0,1,1
4,0,3,35,0,0,8,1,1,1,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27,0,0,13,1,1,1,0,...,0,0,0,0,0,0,0,0,1,0
887,1,1,19,0,0,30,0,1,0,0,...,1,1,0,0,0,0,0,0,1,1
888,0,3,29,1,2,23,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
889,1,1,26,0,0,30,1,1,1,0,...,0,0,1,0,0,0,0,0,0,1
890,0,3,32,0,0,7,1,1,1,1,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_scaled

array([[-1.61413602,  1.22920747, -0.47072241, ..., -0.30335547,
         0.59681695, -0.7769193 ],
       [-0.40055118, -0.50350514, -0.47072241, ..., -0.30335547,
         0.59681695, -0.7769193 ],
       [ 0.81303367,  0.18957991, -0.47072241, ..., -0.30335547,
         0.59681695, -0.7769193 ],
       ...,
       [ 0.81303367,  0.88266495,  1.23056874, ..., -0.30335547,
         0.59681695, -0.7769193 ],
       [-1.61413602, -1.19659018,  0.37992316, ..., -0.30335547,
         0.59681695,  1.28713496],
       [-1.61413602, -0.65752403, -0.47072241, ..., -0.30335547,
         0.59681695, -0.7769193 ]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = knn.predict(X_test_scaled)

In [ ]:
print("KNN Accuracy:", knn.score(X_test_scaled, y_test))

KNN Accuracy: 0.9050279329608939

In [ ]:
report_knn = classification_report(y_test,y_pred_knn)
print(report_knn)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92       105
           1       0.89      0.88      0.88        74

    accuracy                           0.91       179
   macro avg       0.90      0.90      0.90       179
weighted avg       0.90      0.91      0.90       179

In [ ]:
for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    print(k, knn.score(X_test_scaled, y_test))

1 0.9497206703910615
2 0.9329608938547486
3 0.9385474860335196
4 0.9162011173184358
5 0.9050279329608939
6 0.9162011173184358
7 0.9162011173184358
8 0.9217877094972067
9 0.9217877094972067
10 0.9217877094972067

In [ ]:
confusion_matrix(y_test,y_pred_knn)

array([[97,  8],
       [ 9, 65]])